In [1]:
import numpy as np
#Dataset

                             

1.find the country index with maximum gold

In [6]:
import numpy as np

np_olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'OPN', 'GER'])
np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

# Find the index of the country with the maximum gold medals
max_gold_index = np.argmax(np_olympic_country_gold)

print(max_gold_index )


3


2. Print Country with Maximum gold

In [9]:
import numpy as np

np_olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'OPN', 'GER'])
np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

# Find the index of the country with the maximum gold medals
max_gold_index = np.argmax(np_olympic_country_gold)

# Find the country with the maximum gold medals
country_with_max_gold = np_olympic_country[max_gold_index]

print("Country with the maximum gold medals:", country_with_max_gold)


Country with the maximum gold medals: US


3. Find countries with more than 20 gold

medals

In [7]:
import numpy as np

np_olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'OPN', 'GER'])
np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

# Find countries with more than 20 gold medals
countries_with_more_than_20_gold = np_olympic_country[np_olympic_country_gold > 20]

print("Countries with more than 20 gold medals:", countries_with_more_than_20_gold)


Countries with more than 20 gold medals: ['GBR' 'China' 'RUS' 'US']


4. Evaluate the dataset and print the medal:

1. print each country name with number of gold medals 2. print each country name with total number of medals

In [8]:
import numpy as np

np_olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'OPN', 'GER'])
np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
np_olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
np_olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])


print("Country Name\tGold Medals")
for country, gold_medals in zip(np_olympic_country, np_olympic_country_gold):
    print(f"{country}\t\t{gold_medals}")


total_medals = np_olympic_country_gold + np_olympic_country_silver + np_olympic_country_bronze
print("\nCountry Name\tTotal Medals")
for country, total in zip(np_olympic_country, total_medals):
    print(f"{country}\t\t{total}")


Country Name	Gold Medals
GBR		29
China		38
RUS		24
US		46
KOR		13
OPN		7
GER		11

Country Name	Total Medals
GBR		65
China		88
RUS		81
US		103
KOR		28
OPN		38
GER		36


1. Create a 3x3x3 array with random values

In [11]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.random((3, 3, 3))

print(random_array)


[[[0.17156442 0.51369532 0.35255134]
  [0.4898636  0.48015267 0.64053607]
  [0.39311214 0.66042337 0.66487236]]

 [[0.79346655 0.89735577 0.50719209]
  [0.75085497 0.61499588 0.00868542]
  [0.48627412 0.41561357 0.99472763]]

 [[0.53499197 0.02934323 0.04171402]
  [0.71064083 0.01472229 0.03845901]
  [0.04008423 0.58447597 0.79286897]]]


2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill the values 1, 2, 3, 4 just below the diagonal
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the matrix with the checkerboard pattern
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]



4. Normalize a 5x5 random matri

In [20]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.random((5, 5))

# Calculate the mean and standard deviation of the matrix
mean = random_matrix.mean()
std_dev = random_matrix.std()

# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.9203157  0.49387504 0.75587203 0.84700251 0.53316464]
 [0.2869587  0.23247422 0.10032414 0.24620449 0.41659724]
 [0.17909284 0.43474582 0.84190151 0.62137739 0.37170906]
 [0.29545326 0.9078863  0.82890832 0.04255842 0.9229103 ]
 [0.4816192  0.75202143 0.83702448 0.31610178 0.92055068]]

Normalized Matrix:
[[ 1.32823354 -0.17478677  0.74864015  1.06983598 -0.03630782]
 [-0.90407806 -1.09611248 -1.56188481 -1.04771917 -0.44715785]
 [-1.28425893 -0.38319191  1.05185717  0.27460429 -0.60536944]
 [-0.8741384   1.28442521  1.00606174 -1.76548419  1.33737839]
 [-0.21798335  0.73506847  1.03466771 -0.80136121  1.32906172]]


5. How to find common values between two arrays?

In [21]:
import numpy as np

arr1 = np.array([1, 3, 4, 3])
arr2 = np.array([3, 1, 2, 1])

result = np.intersect1d(arr1, arr2)

print("The common elements are:", result)

The common elements are: [1 3]


6. How to get the dates of yesterday, today and tomorrow

In [22]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2023-09-20
Today:  2023-09-21
Tomorrow:  2023-09-22


7. Consider two random array A and B, check if they are equal

In [23]:
import numpy as np
x = np.random.randint(0,3,6)
print("First array:")
print(x)
y = np.random.randint(0,3,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)


First array:
[0 1 2 2 2 2]
Second array:
[1 0 1 2 1 0]
Test above two arrays are equal or not!
False


8.Create random vector of size 10 and replace the maximum value by 0

In [24]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)


Original array:
[0.17176642 0.37001807 0.529574   0.06079148 0.01316151 0.75827831
 0.55625344 0.90952061 0.89227822 0.89960389]
Maximum value replaced by 0:
[0.17176642 0.37001807 0.529574   0.06079148 0.01316151 0.75827831
 0.55625344 0.         0.89227822 0.89960389]


9. How to print all the values of an array?

In [26]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

# Using print to display the entire NumPy array
print(my_array)


[1 2 3 4 5]


10.Subtract the mean of each row of a matri

In [27]:
import numpy as np


matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the matrix
result_matrix = matrix - row_means

print("Original matrix:")
print(matrix)
print("Matrix with row means subtracted:")
print(result_matrix)


Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix with row means subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


12.How to get the diagonal of a dot product?

In [28]:
import numpy as np


given_vector = np.array([10, 20, 30, 40, 50])

# Second vector with indices
indices_vector = np.array([1, 2, 0, 2, 1])

# Create an array of unique indices
unique_indices = np.unique(indices_vector)

# Create a zero-filled result vector
result_vector = np.zeros_like(given_vector)

# Add 1 to the elements at unique indices
result_vector[unique_indices] += 1

# Add the updated result_vector to the given_vector
result_vector += given_vector

print("Given vector:")
print(given_vector)
print("Result vector with 1 added to unique indices:")
print(result_vector)


Given vector:
[10 20 30 40 50]
Result vector with 1 added to unique indices:
[11 21 31 40 50]


12.How to get the diagonal of a dot product?

In [29]:
import numpy as np


A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])


dot_product = np.dot(A, B)

# Get the diagonal elements of the dot product
diagonal = np.diag(dot_product)

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Dot product of A and B:")
print(dot_product)
print("Diagonal elements of the dot product:")
print(diagonal)


Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Dot product of A and B:
[[19 22]
 [43 50]]
Diagonal elements of the dot product:
[19 50]


13.How to find the most frequent value in an array

In [31]:
import numpy as np
x= np.random.randint(0,10,50)
x

array([2, 0, 5, 2, 0, 1, 0, 4, 9, 3, 3, 3, 2, 0, 8, 7, 7, 9, 6, 8, 3, 4,
       5, 3, 1, 8, 8, 1, 7, 1, 7, 8, 9, 9, 4, 5, 3, 8, 7, 6, 9, 5, 7, 4,
       0, 3, 6, 4, 8, 3])

In [33]:


# Use numpy's unique function to get unique values and their counts
unique_values, counts = np.unique(x, return_counts=True)

# Find the index of the maximum count, which corresponds to the most frequent value
most_frequent_index = np.argmax(counts)

# Get the most frequent value
most_frequent_value = unique_values[most_frequent_index]

print("Most frequent value:", most_frequent_value)
print("Frequency:", counts[most_frequent_index])


Most frequent value: 3
Frequency: 8


14.How to get the n largest values of an array

In [34]:
import numpy as np
x = np.arange(10) #0 TO 9
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


15.How to create a record array from a regular array?

In [35]:
import numpy as np

regular_array = np.array([(1, 'Raja', 25),
                          (2, 'Shikhar', 30),
                          (3, 'Sanu', 22)],
                         dtype=[('id', int), ('name', 'U10'), ('age', int)])

# Print the regular array
print("Regular Array:")
print(regular_array)

# Access elements using field names
print("First element - ID:", regular_array['id'][0])
print("First element - Name:", regular_array['name'][0])
print("First element - Age:", regular_array['age'][0])


Regular Array:
[(1, 'Raja', 25) (2, 'Shikhar', 30) (3, 'Sanu', 22)]
First element - ID: 1
First element - Name: Raja
First element - Age: 25


16. How to swap two rows of an array?

In [36]:
# Import numpy
import numpy as np

# Creating a numpy array
arr = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4]])

# Display original array
print("Original aarray:\n",arr,"\n")

# Swapping rows 0th and 2nd
arr[[0,2]] = arr[[2,0]]

# Display result
print("Result:\n",arr)


Original aarray:
 [[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]] 

Result:
 [[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


17. Write python code to reshape to the next dimension of numpy array

In [38]:
data=np.array([11,22,33,44,55]) 
print(data, data.shape, data.ndim)

[11 22 33 44 55] (5,) 1


In [39]:
data2=np.array([[11,22], [33,44], [55,66]]) 
print(data2, data2.ndim)

[[11 22]
 [33 44]
 [55 66]] 2


In [40]:
d2=data.reshape((data.shape[0],1))
d2

array([[11],
       [22],
       [33],
       [44],
       [55]])