In [29]:
from random import random
from numpy import array
from numpy import cumsum
def get_sequence(n_timesteps):
 
    x=array([random() for _ in range(n_timesteps)])
    limit=n_timesteps/4.0
    y=array([0 if x<limit else 1 for x in cumsum(x)])
    return x,y
x,y=get_sequence(15)
print('Input Sequence-x:\n',x)
print()
print('Output-y:\n',y)


Input Sequence-x:
 [0.4552125  0.91263408 0.49852148 0.1709662  0.22105185 0.75745518
 0.10196059 0.89552489 0.29291812 0.77853923 0.15747767 0.79311411
 0.12579638 0.98865109 0.5576534 ]

Output-y:
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]


In [30]:
#Generate Multiple Sequences
def get_sequences(n_sequences,n_timesteps):
    seq_x,seq_y=list(),list()
 
    for _ in range(n_sequences):
        
        x,y=get_sequence(n_timesteps)
        seq_x.append(x)
        seq_y.append(y)
 
    seq_x=array(seq_x).reshape(n_sequences,n_timesteps,1)
    seq_y=array(seq_y).reshape(n_sequences,n_timesteps,1)
    return seq_x,seq_y 


In [31]:
get_sequences(2,15)

(array([[[0.22985048],
         [0.79974722],
         [0.07581553],
         [0.5035688 ],
         [0.23645881],
         [0.04968387],
         [0.18460319],
         [0.20898302],
         [0.63409143],
         [0.63808609],
         [0.39964123],
         [0.08746439],
         [0.96568291],
         [0.82932751],
         [0.37294615]],
 
        [[0.65078276],
         [0.20638263],
         [0.6100204 ],
         [0.72378644],
         [0.72795446],
         [0.2029781 ],
         [0.46181597],
         [0.31365666],
         [0.65608576],
         [0.98205614],
         [0.95214864],
         [0.46256541],
         [0.31274677],
         [0.38975876],
         [0.38119594]]]),
 array([[[0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [1],
         [1],
         [1],
         [1],
         [1]],
 
        [[0],
         [0],
         [0],
         [0],
         [0],
         [0],
       

In [32]:

n_timesteps=15

Build a Bidirectional model


In [33]:
from keras.models import Sequential
from keras.layers import Bidirectional
from keras.layers import TimeDistributed
from keras.layers import Dense,LSTM
model=Sequential()
#bidirectional layer
model.add(Bidirectional(LSTM(50,return_sequences=True),input_shape=(n_timesteps,1)))
#Output layer - time distributed layer
model.add(TimeDistributed(Dense(1,activation='sigmoid')))
#compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print(model.summary())


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional_2 (Bidirecti  (None, 15, 100)           20800     
 onal)                                                           
                                                                 
 time_distributed_2 (TimeDi  (None, 15, 1)             101       
 stributed)                                                      
                                                                 
Total params: 20901 (81.64 KB)
Trainable params: 20901 (81.64 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [34]:
#train the model
x,y=get_sequences(40000,n_timesteps)
model.fit(x,y,epochs=10,batch_size=10)


Epoch 1/10
4000/4000 [==============================] - 25s 5ms/step - loss: 0.0507 - accuracy: 0.9818
Epoch 2/10
4000/4000 [==============================] - 21s 5ms/step - loss: 0.0193 - accuracy: 0.9931
Epoch 3/10
4000/4000 [==============================] - 23s 6ms/step - loss: 0.0150 - accuracy: 0.9943
Epoch 4/10
4000/4000 [==============================] - 28s 7ms/step - loss: 0.0131 - accuracy: 0.9949
Epoch 5/10
4000/4000 [==============================] - 31s 8ms/step - loss: 0.0123 - accuracy: 0.9951
Epoch 6/10
4000/4000 [==============================] - 29s 7ms/step - loss: 0.0111 - accuracy: 0.9957
Epoch 7/10
4000/4000 [==============================] - 26s 7ms/step - loss: 0.0107 - accuracy: 0.9957
Epoch 8/10
4000/4000 [==============================] - 28s 7ms/step - loss: 0.0097 - accuracy: 0.9961
Epoch 9/10
4000/4000 [==============================] - 26s 7ms/step - loss: 0.0095 - accuracy: 0.9962
Epoch 10/10
4000/4000 [==============================] - 26s 6ms/step - l

In [35]:
#Evaluate the model
x,y=get_sequences(100,n_timesteps)
loss,acc=model.evaluate(x,y,verbose=1)
print()
print('Loss: %f, Accuracy: %f'%(loss,acc*100))


4/4 [==============================] - 1s 5ms/step - loss: 0.0066 - accuracy: 0.9987

Loss: 0.006610, Accuracy: 99.866664


In [36]:
# Make prediction
import numpy as np
for _ in range(10):
    x,y=get_sequences(1,n_timesteps)
    yhat=model.predict(x,verbose=0)
    exp,pred=y.reshape(n_timesteps),yhat.reshape(n_timesteps)
 
    print('y=%s, yhat=%s,correct=%s' % (exp,pred,np.array_equal(exp,pred)))


y=[0 0 0 0 0 0 0 1 1 1 1 1 1 1 1], yhat=[7.1137130e-08 1.0862354e-11 4.0433317e-13 4.0518549e-13 7.7467234e-11
 3.3324105e-10 1.7157155e-01 1.0000000e+00 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00],correct=False
y=[0 0 0 0 0 0 1 1 1 1 1 1 1 1 1], yhat=[8.0940931e-12 1.4078472e-08 2.4612391e-12 4.1751834e-13 1.7234577e-11
 3.9963504e-07 9.9999809e-01 1.0000000e+00 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00],correct=False
y=[0 0 0 0 0 0 1 1 1 1 1 1 1 1 1], yhat=[9.7830783e-09 4.7878899e-11 4.6860484e-12 3.8858855e-12 1.0431052e-07
 5.3631067e-07 9.4823986e-01 1.0000000e+00 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00],correct=False
y=[0 0 0 0 0 0 0 1 1 1 1 1 1 1 1], yhat=[2.79620923e-12 1.48061712e-13 1.59153489e-11 5.11264425e-13
 1.04028683e-13 3.38187824e-08 7.57356035e-03 7.94099867e-01
 9.98938084e-01 9.99999821e-01 1.0

In [37]:
#train the model
x,y=get_sequences(40000,n_timesteps)
model.fit(x,y,epochs=10,batch_size=10)

Epoch 1/10
4000/4000 [==============================] - 25s 6ms/step - loss: 0.0091 - accuracy: 0.9963
Epoch 2/10
4000/4000 [==============================] - 29s 7ms/step - loss: 0.0087 - accuracy: 0.9964
Epoch 3/10
4000/4000 [==============================] - 29s 7ms/step - loss: 0.0086 - accuracy: 0.9964
Epoch 4/10
4000/4000 [==============================] - 27s 7ms/step - loss: 0.0083 - accuracy: 0.9966
Epoch 5/10
4000/4000 [==============================] - 26s 7ms/step - loss: 0.0082 - accuracy: 0.9967
Epoch 6/10
4000/4000 [==============================] - 26s 6ms/step - loss: 0.0075 - accuracy: 0.9969
Epoch 7/10
4000/4000 [==============================] - 25s 6ms/step - loss: 0.0075 - accuracy: 0.9970
Epoch 8/10
4000/4000 [==============================] - 25s 6ms/step - loss: 0.0073 - accuracy: 0.9970
Epoch 9/10
4000/4000 [==============================] - 25s 6ms/step - loss: 0.0074 - accuracy: 0.9970
Epoch 10/10
4000/4000 [==============================] - 26s 7ms/step - l

In [38]:
# Make prediction
import numpy as np
for _ in range(10):
    x,y=get_sequences(1,n_timesteps)
    ypred=model.predict(x,verbose=0)
    actual,pred=y.reshape(n_timesteps),ypred.reshape(n_timesteps)
 
    print('y=%s, ypred=%s,correct=%s' % (actual,pred,np.array_equal(actual,ypred)))


y=[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1], ypred=[3.8960735e-13 6.3818111e-09 4.6424626e-13 3.7229172e-13 6.9832673e-09
 4.3525774e-06 9.6855396e-03 3.8579595e-03 9.9999976e-01 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00],correct=False
y=[0 0 0 0 0 0 0 1 1 1 1 1 1 1 1], ypred=[1.9045827e-10 1.7039963e-11 3.8465205e-13 1.5463077e-10 2.1476258e-10
 2.3255720e-14 7.6210815e-11 7.8184831e-01 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00],correct=False
y=[0 0 0 0 0 1 1 1 1 1 1 1 1 1 1], ypred=[2.3310369e-08 1.4446129e-12 2.0794472e-10 3.3395322e-09 3.8911580e-04
 3.0836806e-01 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00],correct=False
y=[0 0 0 0 0 0 0 1 1 1 1 1 1 1 1], ypred=[4.8401363e-14 2.3379540e-10 1.2191246e-12 9.6756514e-09 1.3166703e-12
 6.7951810e-06 4.4919401e-02 1.0000000e+00 1.0000000e+00 1.0000000e+00
 1.0000000